apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry-operator:6.1.0.0
    init: confluentinc/cp-init-container-operator:6.1.0.0
