apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  storageClass:
    name: standard
  image:
    application: confluentinc/cp-zookeeper-operator:6.1.0.0
    init: confluentinc/cp-init-container-operator:6.1.0.0
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi